#!/usr/bin/env bash
node ./node_modules/grunt-cli/bin/grunt clean

if [ -d "node_modules/bower" ]; then
  node ./node_modules/bower/bin/bower install
  node ./node_modules/grunt-cli/bin/grunt
else
  echo "bower not installed?"
fi
